apiVersion: apps/v1
kind: Deployment
metadata:
  name: favourite-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: favourite-service
  template:
    metadata:
      labels:
        app: favourite-service
    spec:
      containers:
      - name: favourite-service
        image: santiagoprado21/favourite-service-ecommerce-boot:latest
        ports:
        - containerPort: 8800
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: SPRING_ZIPKIN_BASE-URL
          value: "http://zipkin:9411"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://service-discovery-container:8761/eureka/"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8800
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8800
          initialDelaySeconds: 60
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: favourite-service
  namespace: dev
spec:
  selector:
    app: favourite-service
  ports:
  - port: 8800
    targetPort: 8800
  type: ClusterIP 